/* ----------------- ADDRESS TABLE ----------------- */
CREATE SEQUENCE SEQ_ADDRESS;

CREATE TABLE TBL_ADDRESS(
	ADDRESS_NUMBER NUMBER,
	ADDRESS_MAIN VARCHAR2(100),
	ADDRESS_DETAIL VARCHAR2(100),
	ADDRESS_STATUS VARCHAR2(50) DEFAULT '기본배송지',
	ADDRESS_RECEIVE_PERSON VARCHAR2(50),
	ADDRESS_RECEIVE_PHONE_NUMBER VARCHAR2(50),
	MEMBER_NUMBER NUMBER,
	CONSTRAINT FK_ADDRESS FOREIGN KEY(MEMBER_NUMBER)
	REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

SELECT * FROM TBL_ADDRESS;
DROP TABLE TBL_ADDRESS;

INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '서울특별시 관악구 신림동', '1234-1', '기본배송지', '홍길동', '01012341234', 81);
INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '제주특별시 서귀포 2181', '231ȣ', '배송지', '홍회원', '01011112222', 81);
INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '서울특별시 강남구 역삼동 150', '241길 112', '배송지', '김사과', '01011112222', 81);
INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '울산광역시 화서동 1-2', '201호', '기본배송지', '이순신', '01011112222', 82);
/* ----------------------------------------------------- */