/* ----------------- ADDRESS TABLE ----------------- */
CREATE SEQUENCE SEQ_ADDRESS;

CREATE TABLE TBL_ADDRESS(
	ADDRESS_NUMBER NUMBER,
	ADDRESS_MAIN VARCHAR2(100),
	ADDRESS_DETAIL VARCHAR2(100),
	ADDRESS_STATUS VARCHAR2(50) DEFAULT '배송지',
	ADDRESS_RECEIVE_PERSON VARCHAR2(50),
	ADDRESS_RECEIVE_PHONE_NUMBER VARCHAR2(50),
	MEMBER_NUMBER NUMBER,
	CONSTRAINT FK_ADDRESS FOREIGN KEY(MEMBER_NUMBER)
	REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

SELECT * FROM TBL_ADDRESS;
DROP TABLE TBL_ADDRESS;

INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '서울특별시 관악구 신림동', '1234-1', '기본배송지', '홍길동', '01012341234', 1);
INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '제주특별자치도 제주시 영평동 2181', '231호', '배송지', '홍형제', '01011112222', 1);
INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '인천 연수구 새말로 150', '241길 112', '배송지', '홍길동', '01011112222', 1);
INSERT INTO TBL_ADDRESS
VALUES(SEQ_ADDRESS.NEXTVAL, '서울 관악구 관악산나들길 1-2', '(신림동)', '기본배송지', '김사과', '01011112222', 3);
/* ----------------------------------------------------- */