/* ----------------- CART TABLE ----------------- */
CREATE TABLE TBL_CART
(
	MEMBER_NUMBER number NOT NULL,
	PRODUCT_NUMBER number NOT NULL,
	CART_COUNT NUMBER,
	CONSTRAINT FK_CART_MEMBER FOREIGN KEY (MEMBER_NUMBER)
	REFERENCES TBL_MEMBER (MEMBER_NUMBER),
	CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (PRODUCT_NUMBER)
	REFERENCES TBL_PRODUCT (PRODUCT_NUMBER)
);

DROP TABLE TBL_CART;
SELECT * FROM TBL_CART;
/* ----------------------------------------------------- */
