/* ----------------- ORDER TABLE ----------------- */
CREATE SEQUENCE SEQ_ORDER;

CREATE TABLE TBL_ORDER
(
	ORDER_NUMBER number PRIMARY KEY,
	ORDER_DATE DATE DEFAULT SYSDATE,
	ORDER_TOTAL_AMOUNT number,
	ORDER_DELIVERY_DATE date,
	ORDER_DELIVERY_ADRRESS varchar2(200),
	ORDER_DELIVERY_ADRRESS_DETAIL varchar2(200),
	ORDER_SHIPPING_PLACE varchar2(100),
	MEMBER_NUMBER number,
	CONSTRAINT FK_ORDER FOREIGN KEY(MEMBER_NUMBER)
	REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

SELECT * FROM TBL_ORDER;
DROP TABLE TBL_ORDER;

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 2, 6000, '����Ư���� ���Ǳ� �Ÿ���', '1234-1', 26);

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 5, '100000', '����Ư���� ���Ǳ� �Ÿ���', '1234-1', 26);

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 3, '60000', '����Ư����ġ�� ���ֽ� ���� 2181', '231ȣ', 1);

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 1, '10000', '���� ���Ǳ� ���ǻ곪��� 1-2', '(�Ÿ���)', 3);
/* ----------------------------------------------------- */

SELECT * FROM TBL_ORDER_DETAIL;
CREATE SEQUENCE SEQ_ORDER_DETAIL;

CREATE TABLE TBL_ORDER_DETAIL(
	ORDER_DETAIL_NUMBER NUMBER PRIMARY KEY,
    ORDER_DETAIL_COUNT NUMBER,
    ORDER_DETAIL_PRICE NUMBER,
    ORDER_DETAIL_DELIVERY_STATE VARCHAR2(10),
    ORDER_DETAIL_TOTAL_AMOUNT NUMBER,
    ORDER_NUMBER NUMBER,
    PRODUCT_NUMBER NUMBER,
    CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY(ORDER_NUMBER)
	REFERENCES TBL_ORDER(ORDER_NUMBER),
    CONSTRAINT FK__DETAIL_PRODUCT FOREIGN KEY(PRODUCT_NUMBER)
	REFERENCES TBL_PRODUCT(PRODUCT_NUMBER)
);