/* ----------------- ORDER TABLE ----------------- */
CREATE SEQUENCE SEQ_ORDER;

CREATE TABLE TBL_ORDER
(
	ORDER_NUMBER number PRIMARY KEY,
	ORDER_DATE DATE DEFAULT SYSDATE,
	ORDER_TOTAL_AMOUNT number,
	ORDER_DELIVERY_DATE date,
	ORDER_DELIVERY_ADRRESS varchar2(200),
	ORDER_DELIVERY_ADRRESS_DETAIL varchar2(200),
	ORDER_SHIPPING_PLACE varchar2(100),
	MEMBER_NUMBER number,
	CONSTRAINT FK_ORDER FOREIGN KEY(MEMBER_NUMBER)
	REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

SELECT * FROM TBL_ORDER;
DROP TABLE TBL_ORDER;

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 2, '20000', '서울특별시 관악구 신림동', '1234-1', 1);

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 5, '100000', '서울특별시 관악구 신림동', '1234-1', 1);

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 3, '60000', '제주특별자치도 제주시 영평동 2181', '231호', 1);

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, SYSDATE, 1, '10000', '서울 관악구 관악산나들길 1-2', '(신림동)', 3);
/* ----------------------------------------------------- */
