CREATE SEQUENCE SEQ_PARTNER;
DROP TABLE TBL_PARTNER;

CREATE TABLE TBL_PARTNER(
	PARTNER_NUMBER NUMBER CONSTRAINT PK_PARTNER PRIMARY KEY,
	MEMBER_NUMBER NUMBER,
	PARTNER_STORE_NAME VARCHAR2(100),
	PARTNER_REGISTRATION_NUMBER VARCHAR2(100),
	PARTNER_OWNER_NAME VARCHAR2(25),
	PARTNER_OWNER_EMAIL VARCHAR2(100),
	PARTNER_STORE_ADDRESS VARCHAR2(200),
	PARTNER_OWNER_PHONE_NUMBER VARCHAR2(25),
	CONSTRAINT FK_MEMBER FOREIGN KEY(MEMBER_NUMBER)
	REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

INSERT INTO TBL_PARTNER
(PARTNER_NUMBER, MEMBER_NUMBER, PARTNER_STORE_NAME, PARTNER_REGISTRATION_NUMBER, PARTNER_OWNER_NAME, PARTNER_OWNER_EMAIL, PARTNER_STORE_ADDRESS, PARTNER_OWNER_PHONE_NUMBER)
VALUES(SEQ_PARTNER.NEXTVAL, 1, '디데이', '111-22-3333', '강희수', 'dday@gmail.com', '06236 서울 강남구 테헤란로 146 13층', '02-123-1234');


SELECT * FROM TBL_PARTNER;
