/* ----------------- POINT TABLE ----------------- */
CREATE SEQUENCE SEQ_POINT;

CREATE TABLE TBL_POINT
(
	POINT_NUMBER NUMBER PRIMARY KEY,
	MEMBER_NUMBER NUMBER,
	POINT_REMAIN NUMBER,
	POINT_PRICE NUMBER,
	POINT_CONTENT VARCHAR2(200),
	POINT_DATE DATE DEFAULT SYSDATE,
	POINT_END_DATE DATE,
	POINT_TYPE VARCHAR2(10),
	CONSTRAINT FK_POINT FOREIGN KEY (MEMBER_NUMBER)
	REFERENCES TBL_MEMBER (MEMBER_NUMBER)
);

SELECT * FROM TBL_POINT;
DROP TABLE TBL_POINT;

INSERT INTO TBL_POINT
VALUES(SEQ_POINT.NEXTVAL, 81, 2000, 2000, '[구매 적립] 2000원 적립!', SYSDATE, ADD_MONTHS(SYSDATE, 1), '적립');
INSERT INTO TBL_POINT
VALUES(SEQ_POINT.NEXTVAL, 81, 5000, 3000, '[구매 적립] 3000원 적립!', SYSDATE, ADD_MONTHS(SYSDATE, 1), '적립');
INSERT INTO TBL_POINT(POINT_NUMBER, MEMBER_NUMBER, POINT_REMAIN, POINT_PRICE, POINT_CONTENT, POINT_DATE, POINT_TYPE)
VALUES(SEQ_POINT.NEXTVAL, 81, 4800, 200, '[구매 사용] 200원 사용!', SYSDATE, '사용');
INSERT INTO TBL_POINT
VALUES(SEQ_POINT.NEXTVAL, 3, 2000, '[구매 적립] 2000원 적립!', SYSDATE, ADD_MONTHS(SYSDATE, 1));

SELECT POINT_REMAIN
FROM 
 (
  SELECT POINT_REMAIN
  FROM TBL_POINT
  ORDER BY POINT_NUMBER DESC
 )
WHERE ROWNUM = 1;

/* ----------------------------------------------------- */