CREATE TABLE TBL_PRODUCT_LIKE(
	PRODUCT_NUMBER NUMBER,
	MEMBER_NUMBER NUMBER,
	CONSTRAINT FK_PRODUCT_LIKE FOREIGN KEY (PRODUCT_NUMBER)
	REFERENCES TBL_PRODUCT (PRODUCT_NUMBER),
	CONSTRAINT FK_MEMBER_LIKE FOREIGN KEY (MEMBER_NUMBER)
	REFERENCES TBL_MEMBER (MEMBER_NUMBER),
	CONSTRAINT PK_PRODUCT_LIKE PRIMARY KEY(PRODUCT_NUMBER, MEMBER_NUMBER)
);

SELECT * FROM TBL_PRODUCT_LIKE;

INSERT INTO TBL_PRODUCT_LIKE
VALUES(1, 26);

SELECT L.PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_SALE_PRICE
FROM TBL_PRODUCT_LIKE L INNER JOIN TBL_PRODUCT P
ON L.PRODUCT_NUMBER=P.PRODUCT_NUMBER
WHERE L.MEMBER_NUMBER=26;

DROP TABLE TBL_PRODUCT_LIKE;