CREATE SEQUENCE SEQ_DDAY;

CREATE TABLE TBL_PRODUCT(
PRODUCT_NUMBER NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
MEMBER_NUMBER NUMBER,
PRODUCT_NAME VARCHAR2(100),
PRODUCT_CATEGORY VARCHAR2(100),
PRODUCT_PRICE NUMBER,
PRODUCT_STOCK NUMBER,
PRODUCT_MANUFACTURE_DATE DATE,
PRODUCT_EXPIRATION_DATE DATE,
PRODUCT_ONELINE_INFORMATION VARCHAR2(1000),
PRODUCT_INFORMATION VARCHAR2(1000),
PRODUCT_THUMBNAIL_NAME VARCHAR2(100),
PRODUCT_MAIN_IMAGE_NAME VARCHAR2(100),
PRODUCT_REGIST_DATE DATE,
PRODUCT_MODIFY_DATE DATE,
PRODUCT_VIEW_COUNT NUMBER,
PRODUCT_TODAY_SALE DATE,
PRODUCT_OPEN_HOURS DATE,
PRODUCT_SALE_PERCENT NUMBER,
PRODUCT_SALE_PRICE NUMBER,
CONSTRAINT FK_PRODUCT FOREIGN KEY (MEMBER_NUMBER) REFERENCES
TBL_MEMBER (MEMBER_NUMBER)
);
SELECT * FROM (
SELECT /*INDEX_DESC (TBL_PRODUCT PK_PRODUCT) */ ROWNUM RN, PRODUCT_NUMBER, PRODUCT_THUMBNAIL_NAME, PRODUCT_PRICE, PRODUCT_INFORMATION
FROM TBL_PRODUCT
WHERE PRODUCT_NUMBER > 0 AND ROWNUM >0 AND ROWNUM <=20
)
WHERE RN > 10

SELECT PRODUCT_NUMBER, PRODUCT_THUMBNAIL_NAME,PRODUCT_PRICE, PRODUCT_INFORMATION
FROM
(SELECT ROWNUM R, D2.*
FROM
(
	SELECT P.* FROM TBL_PRODUCT  P
	ORDER BY PRODUCT_NUMBER DESC
) D2
	WHERE ROWNUM <=20
	)WHERE R > 10;

SELECT * FROM TBL_PRODUCT
ORDER BY PRODUCT_NUMBER asc;


INSERT INTO TBL_PRODUCT (PRODUCT_NUMBER, PRODUCT_THUMBNAIL_NAME,PRODUCT_PRICE, PRODUCT_INFORMATION,PRODUCT_CATEGORY)
(SELECT SEQ_DDAY.NEXTVAL, PRODUCT_THUMBNAIL_NAME,PRODUCT_PRICE, PRODUCT_INFORMATION,PRODUCT_CATEGORY FROM TBL_PRODUCT);

  SELECT COUNT(1) OVER () T0T_CNT,PRODUCT_NAME,PRODUCT_PRICE, PRODUCT_INFORMATION,PRODUCT_THUMBNAIL_NAME, PRODUCT_MAIN_IMAGE_NAME FROM TBL_PRODUCT
        WHERE PRODUCT_THUMBNAIL_NAME LIKE '%김%';
       
        SELECT COUNT(1) AS totCnt FROM TBL_PRODUCT;
       
       SELECT * FROM TBL_PRODUCT tp
       WHERE PRODUCT_CATEGORY IS NULL;
       
      
      INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(1, 1, '[연세우유] 전용목장우유 900mL', '8', 2070, '[연세우유] 전용목장우유 900mL', '가격, 퀄리티 모두 만족스러운 1A등급 우유', '1637154205701l0', 34, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(2, 2, '[우유공식] 무항생제 우유 900mL', '8', 3200, '[우유공식] 무항생제 우유 900ml', '목장의 과학으로 만든 우유', '1607314173577l0', 123, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(3, 3, '[서울우유] 나 100% 우유 1000mL', '8', 2890, '[서울우유] 나 100% 우유 1000mL', '서울우유의 믿을 수 있는 품질! 우리나라 대표 1A 우유', '1637921690477l0', 56, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(4, 4, '[상하목장] 유기농 우유 & 저지방 우유 750mL 2종', '8', 5200, '[상하목장] 유기농 우유 & 저지방 우유 750mL 2종', '행복한 소가 만들어낸 행복한 한 모금 ', '1646638953618l0', 33, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 10, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(5, 4, '[서울우유] 나 100% 우유 1.8L', '8', 5350, '[서울우유] 나 100% 우유 1.8L', '서울우유의 믿을 수 있는 품질! 든든한 용량 1등급 우유', '1583462074699l0', 76, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 10, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(6, 2, '[연세우유] 저지방 전용 목장 우유 900mL', '8', 2300, '[연세우유] 저지방 전용목장 우유 900mL', '가격, 퀄리티 모두 만족스러운 1A등급 저지방 우유', '1656650352942l0', 89, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(7, 3, '[상하목장] 유기농 우유 900mL', '8', 4850, '[상하목장] 유기농 우유 900mL', '넉넉하게 만나는 유기농 우유', '1645694606714l0', 11, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(8, 4, '[매일] 소화가 잘되는 우유 930mL 2종', '8', 3580, '[매일] 소화가 잘되는 우유 930mL 2종', '유당은 제거하고 칼슘은 높인', '1653034416453l0', 22, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(9, 1, '[매일] 오리지널 우유 1.5L', '8', 4850, '[매일] 오리지널 우유 1.5L', '세균수 1A 등급의 신선한 우유', '1585707320997l0', 22, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(10, 3, '[매일] 매일우유 후레쉬팩 오리지널 900mL', '8', 2850, '[매일] 매일우유 후레쉬팩 오리지널 900mL', '신선함과 고소함을 더한 살균 우유', '1653034416980l0', 76, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(11, 1, '[범산목장] 목초먹인 유기농 우유 1000mL', '8', 6210, '[범산목장] 목초먹인 유기농 우유 1000mL', '강원도 목초 우유를 대용량으로', '1575961965803l0', 13, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 10, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(12, 1, '[파스퇴르] 저온살균 흰우유 2300mL', '8', 6980, '[파스퇴르] 저온살균 흰우유 2300mL', '저온장시간 살균법으로 가장 신선한 우유 파스퇴르', '1657604925195l0', 1, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(13, 2, '[농협풍산김치] 맛김치 800g', '5', 9000, '[농협풍산김치] 맛김치 800g', '먹기 좋게 썬 간편 김치', '1657275404400l0', 154, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(14, 3, '[Kurly''s] 시원한 배추김치', '5', 12900, '[Kurly''s] 시원한 배추김치', '횡성한우 사골육수의 깊은 감칠맛', '1657604925195l0', 4, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(15, 4, '[비비고] 썰은 배추김치', '5', 7300, '[비비고] 썰은 배추김치', '간편하게 바로 먹는 맛있는 비비고 김치!', '1657695159818l0', 123, TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', '맛있어요', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', TIMESTAMP '2022-12-02 00:00:00.000000', 5, 2000);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(16, 1, '[조선호텔김치] 배추김치', '5', 28000, '[조선호텔김치] 배추김치', '조선호텔 대표 명품김치', '1657530036493l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(17, 2, '[비비고] 김치 볶음', '5', 3200, '[비비고] 김치 볶음', '100℃ 직화 솥에서 달달 볶아낸 볶음 김치!', '1646976060594l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(18, 3, '[해담촌] 포기김치', '5', 6400, '[해담촌] 포기김치', '시원하고 깊은 맛을 담은', '1657275752813l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(19, 4, '[비비고] 총각 김치', '5', 7920, '[비비고] 총각 김치', '아삭하고 깔끔한 맛이 일품 ', '1657695311852l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(20, 1, '[피코크] 조선호텔 남도식 김치 1.9kg', '5', 26800, '[피코크] 조선호텔 남도식 김치 1.9kg', '깨끗하고 시원한 그 맛', '1657528059797l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(21, 2, '[농협풍산김치] 포기김치 1kg', '5', 9800, '[농협풍산김치] 포기김치 1kg', '부담없이 먹는 매일 김치', '1657602674517l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(22, 3, '[종가] 포기김치 2.3kg', '5', 24500, '[종가] 포기김치 2.3kg', '저온 발효로 더 맛있어진 집 김치', '1657275404400l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(23, 4, '[해담촌] 파김치', '5', 6600, '[해담촌] 파김치', '칼칼한 맛이 살아 있는', '1657603620440l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(24, 1, '[한국농협김치] 썰은배추김치 400g', '5', 4680, '[한국농협김치] 썰은배추김치 400g', '간편하게 즐기는 깊은 맛', '1657604925195l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(25, 2, '[상하치즈] 유기농 아이치즈 3종 (10매입)', '10', 5720, '[상하치즈] 유기농 아이치즈 3종 (10매입)', '탄탄한 영양학적 설계로 이루어진 우리 아이의 건강 간식', '1646715269993l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(26, 3, '[상하치즈] 리코타치즈', '10', 6050, '[상하치즈] 리코타치즈', '국산 원유로 만든 신선 치즈', '1622006382671l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(27, 4, '[상하치즈] 브리 자연치즈', '10', 6050, '[상하치즈] 브리 자연치즈', '부드러운 풍미의 숙성 치즈', '1621918870521l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(28, 1, '[상하치즈] 유기농 어린이 고칼슘 치즈', '10', 5720, '[상하치즈] 유기농 어린이 고칼슘 치즈', '유기농 자연 치즈로 만든', '1618892772670l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(29, 2, '[알라] 슬라이스 치즈 3종', '10', 6380, '[알라] 슬라이스 치즈 3종', '한 장씩 꺼내쓰기 좋은 만능 치즈', '163901953861l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(30, 3, '[상하치즈] 샐러드용 슈레드 치즈', '10', 4800, '[상하치즈] 샐러드용 슈레드 치즈', '뿌리면 완성되는 고품격 치즈 요리 ', '1636097453253l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(31, 4, '[임실치즈] 스모크 치즈 64g', '10', 6050, '[임실치즈] 스모크 치즈 64g', '캔디처럼 즐기는 훈연 치즈', '1646211717369l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(32, 1, '[임실치즈] 임실구워먹는치즈 280g', '10', 5490, '[임실치즈] 임실구워먹는치즈 280g', '노릇노릇 쫀득쫀득한 반전 치즈', '1575955025258l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(33, 2, '[램노스] 과일치즈 5종', '10', 6900, '[램노스] 과일치즈 5종', '상큼하고 달콤하게 즐기는 치즈', '1653034817547l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(34, 3, '[벨지오이오소] 부라타 치즈', '10', 5382, '[벨지오이오소] 부라타 치즈', '버터처럼 부드러운 크림이 들어있는 생치즈 ', '1653034120711l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(35, 4, '[서울우유] 쭈욱 늘어나는 체다치즈', '10', 14900, '[서울우유] 쭈욱 늘어나는 체다치즈', '체다와 모차렐라 치즈와의 만남', '1570154531327l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(36, 1, '[상하치즈] 지방을 낮춘 고단백 치즈 270g', '10', 5500, '[상하치즈] 지방을 낮춘 고단백 치즈 270g', '고단백으로 더욱 든든', '1655791861265l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(37, 2, '[fruit salon] 간편 컷팅과일 150g', '2', 4300, '[fruit salon] 간편 컷팅과일 150g', '손쉽게 즐기는 5가지 과일', '1617331435965l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(38, 3, '칠레산 블루베리 2종 (택1)', '2', 2300, '칠레산 블루베리 2종 (택1)', '톡톡 번져가는 상큼함 가득', '1637923286553l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(39, 4, '유명산지 한판딸기 500g', '2', 6500, '유명산지 한판딸기 500g', '유명산지에서 전하는 제철 딸기', '1608801577622l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(40, 1, 'GAP 샤인머스캣 650g', '2', 10900, 'GAP 샤인머스캣 650g', '상큼함으로 무장한 연둣빛 포도', '1637922887777l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(41, 2, '[KF365] 유명산지 고당도사과 1.5kg (5~6입)', '2', 1200, '[KF365] 유명산지 고당도사과 1.5kg (5~6입)', '아삭아삭 달콤한 제철과일', '1538466010000_l', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(42, 3, '당도선별 서귀포 노지 감귤 1.5kg', '2', 4300, '당도선별 서귀포 노지 감귤 1.5kg', '언제 먹어도 반가운 과일', '1648207113878l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(43, 4, '새콤달콤 당도선별 제주 노지감귤 2.5kg (2S~M)', '2', 5659, '새콤달콤 당도선별 제주 노지감귤 2.5kg (2S~M)', '제주의 달콤함을 넉넉하게 즐기는 ', '1648207113878l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(44, 1, '시나노골드 (금사과) 1.3kg (5~7입)', '2', 1200, '시나노골드 (금사과) 1.3kg (5~7입)', '달콤함과 새콤함의 적절한 조화, 황금빛 시나노골드', '1538466010000_l', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(45, 2, '[자연실록] 무항생제 닭 다리살 (정육) 500g', '4', 7743, '[자연실록] 무항생제 닭 다리살 (정육) 500g', '100g 당1,780원', '163842816248l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(46, 3, '[PPUL] 1++ 한우 정육 구이 200g (냉장)', '4', 17000, '[PPUL] 1++ 한우 정육 구이 200g (냉장)', '100g당 가격: 8,500원', '1573111080411l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(47, 4, '[PPUL] 1++ 한우 정육 슬라이스 200g (냉장)', '4', 17000, '[PPUL] 1++ 한우 정육 슬라이스 200g (냉장)', '100g당 가격: 8,500원', '1573107099611l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(48, 1, '[1등급 한우] 등심 국거리 200g (냉장)', '4', 15900, '[1등급 한우] 등심 국거리 200g (냉장)', '100g당 판매가 : 7,950원', '1637927391124l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(49, 2, '[레인저스벨리] 호주산 블랙앵거스 윗등심 스테이크 300g (냉장)', '4', 18900, '[레인저스벨리] 호주산 블랙앵거스 윗등심 스테이크 300g (냉장)', '100g당 판매가: 6,300원', '1637927391124l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(50, 3, '[하림] 치킨스테이크 다리살 320g', '4', 5920, '[하림] 치킨스테이크 다리살 320g', '근사하게 즐기는 국내산 닭다리살', '163842816248l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(51, 4, '체어맨스리저브 미국산 LA갈비 세트 2.8kg', '4', 189000, '체어맨스리저브 미국산 LA갈비 세트 2.8kg', '189,000원', '1628825639114l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(52, 1, '[레인저스벨리] 호주산 블랙앵거스 우둔 300g (냉장)', '4', 10900, '[레인저스벨리] 호주산 블랙앵거스 우둔 300g (냉장)', '100g당 판매가: 3300원', '1637927457796l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(53, 2, '[레인저스벨리] 호주산 블랙앵거스 큐브형 우둔 300g (냉장)', '4', 10900, '[레인저스벨리] 호주산 블랙앵거스 큐브형 우둔 300g (냉장)', '100g당 판매가: 3300원', '1637927437689l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(54, 3, '[콜린스 다이닝] 쯔란갈비 winter edition', '4', 26900, '[콜린스 다이닝] 쯔란갈비 winter edition', '이국적인 맛과 향이 깃든', '1573107099611l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, MEMBER_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_THUMBNAIL_NAME, PRODUCT_INFORMATION, PRODUCT_MAIN_IMAGE_NAME, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_REGIST_DATE, PRODUCT_MODIFY_DATE, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, PRODUCT_SALE_PERCENT, PRODUCT_SALE_PRICE)
VALUES(55, 4, '[소호好담] 태우1+한우 실속 모둠세트(냉동)', '4', 78900, '[소호好담] 태우1+한우 실속 모둠세트(냉동)', '국거리200gx2, 등심200g, 불고기200g', '1600323624579l0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

      