CREATE SEQUENCE SEQ_DDAY;

/* ----------------- MEMBER TABLE ----------------- */
CREATE TABLE TBL_MEMBER(
MEMBER_NUMBER NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
MEMBER_ID VARCHAR2(20),
MEMBER_PW VARCHAR2(20),
MEMBER_NAME VARCHAR2(25),
MEMBER_EMAIL VARCHAR2(50),
MEMBER_PHONE_NUMBER VARCHAR2(11),
MEMBER_ADDRESS VARCHAR2(100),
MEMBER_ADDRESS_DETAIL VARCHAR2(100),
MEMBER_GENDER VARCHAR2(25),
MEMBER_BIRTH DATE,
MEMBER_SIGNUP_DATE DATE,
MEMBER_TYPE VARCHAR2(25),
MEMBER_STATUS VARCHAR2(10)
);
/* ----------------- PRODUCT TABLE ----------------- */
CREATE TABLE TBL_PRODUCT(
PRODUCT_NUMBER NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
MEMBER_NUMBER NUMBER,
PRODUCT_NAME VARCHAR2(100),
PRODUCT_CATEGORY VARCHAR2(100),
PRODUCT_PRICE NUMBER,
PRODUCT_STOCK NUMBER,
PRODUCT_MANUFACTURE_DATE DATE,
PRODUCT_EXPIRATION_DATE DATE,
PRODUCT_ONELINE_INFOMATION VARCHAR2(1000),
PRODUCT_INFOMATION VARCHAR2(1000),
PRODUCT_THUMBNAIL_NAME VARCHAR2(100),
PRODUCT_MAIN_IMAGE_NAME VARCHAR2(100),
PRODUCT_REGIST_DATE DATE,
PRODUCT_MODIFY_DATE DATE,
PRODUCT_TODAY_SALE DATE,
PRODUCT_OPEN_HOURS DATE,
PRODUCT_SALE_PERCENT NUMBER,
PRODUCT_SALE_PRICE NUMBER,
CONSTRAINT FK_PRODUCT FOREIGN KEY (MEMBER_NUMBER) REFERENCES 
TBL_MEMBER (MEMBER_NUMBER)
);

INSERT INTO TBL_PRODUCT(PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_INFORMATION, PRODUCT_SALE_PERCENT, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, MEMBER_NUMBER) 
VALUES(SEQ_PRODUCT.NEXTVAL, '토마토','채소','3000','10','20221124', '20221210', '신선한 채소에요','유기농으로 재배되어 안심하고 먹을 수 있어요','10','20221201', to_date('20221202 23:00', 'yyyymmdd hh24:mi'), 2);

INSERT INTO TBL_PRODUCT(PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_INFORMATION, PRODUCT_SALE_PERCENT, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, MEMBER_NUMBER) 
VALUES(SEQ_PRODUCT.NEXTVAL, '당근','채소','2000','10','20221125', '20221210', '신선한 채소에요','유기농으로 재배되어 안심하고 먹을 수 있어요','50','20221201', to_date('20221202 23:00', 'yyyymmdd hh24:mi'), 2);

INSERT INTO TBL_PRODUCT(PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_INFORMATION, PRODUCT_SALE_PERCENT, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, MEMBER_NUMBER) 
VALUES(SEQ_PRODUCT.NEXTVAL, '아아','생수.음료.우유.커피','1700','10','20221124', '20221205', '아아시원해요','머신으로 내려마시는것 만큼 맛있어요','30','20221201', to_date('20221202 23:00', 'yyyymmdd hh24:mi'), 5);

INSERT INTO TBL_PRODUCT(PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_INFORMATION, PRODUCT_SALE_PERCENT, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, MEMBER_NUMBER) 
VALUES(SEQ_PRODUCT.NEXTVAL, '요거트','생수.음료.우유.커피','5000','10','20221128', '20221207', '꾸덕해요','목이 막힐 정도로 꾸덕한 요거트 여기있습니다!','60','20221201', to_date('20221202 23:00', 'yyyymmdd hh24:mi'), 5);

INSERT INTO TBL_PRODUCT(PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_PRICE, PRODUCT_STOCK, PRODUCT_MANUFACTURE_DATE, PRODUCT_EXPIRATION_DATE, PRODUCT_ONELINE_INFORMATION, PRODUCT_INFORMATION, PRODUCT_SALE_PERCENT, PRODUCT_TODAY_SALE, PRODUCT_OPEN_HOURS, MEMBER_NUMBER) 
VALUES(SEQ_PRODUCT.NEXTVAL, '물','생수.음료.우유.커피','6000','10','20221124', '20231110', '지하 암반수','물 맛이 다릅니다. 드셔보시면 알게 되실거에요','20','20221201', to_date('20221202 23:00', 'yyyymmdd hh24:mi'), 5);

DROP TABLE  TBL_PRODUCT ;
SELECT * FROM TBL_PRODUCT;
SELECT *FROM TBL_MEMBER;